#!/usr/bin/env bash

##########################################################################
## NAVIGATION
alias ~="cd ~"

alias ~stg="cd ${STORAGE}"
alias ~dwl="cd ${DOWNLOADS}"
alias ~prj="cd ${PROJECTS}"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

##########################################################################
## BASH COMMANDS

# Enable aliases to be sudo’ed
alias sudo="sudo "

# Create and notify any necessary parent folder
alias mkdir="mkdir -pv"

# Copy with progress bar
alias cpv="rsync -ah --info=progress2"

# Show my external ip
alias myip="curl ipinfo.io/ip"

##########################################################################
## WINDOWS COMMANDS
alias ipconfig="cmd.exe /c ipconfig"

##########################################################################
## PROGRAMS
alias xsrv="'${WIN_PF}/Mobatek/MobaXterm/MobaXterm.exe' & "
alias chrome="cmd.exe /c start chrome"
alias chromei="cmd.exe /c start chrome -incognito"
alias explorer="cmd.exe /c start explorer ."
alias npp="cmd.exe /c start notepad++"
