#!/usr/bin/env bash

WIN_USER=$(cmd.exe /c "echo %USERNAME%" | sed -e 's/\r//g') 2> /dev/null

##########################################################################
## PATHS

export WIN_ROOT="/mnt/c"
export WIN_PF="${WIN_ROOT}/Program Files"
export WIN_PF86="${WIN_ROOT}/Program Files (x86)"

export WIN_PROFILES="/mnt/d/users"
export WIN_HOME="${WIN_PROFILES}/${WIN_USER}"

export STORAGE="/mnt/e"
export DOWNLOADS="${STORAGE}/Downloads"
export PROJECTS="${STORAGE}/Projetos"

##########################################################################
## DEFAULTS

export BROWSER="${WIN_PF86}/Google/Chrome/Application/chrome.exe"
export EDITOR=nvim
export VISUAL=nvim
#export PAGER

##########################################################################
## MISC

# openssl
export RANDFILE="${XDG_DATA_HOME}/openssl/rnd"

export GNUPGHOME="${XDG_DATA_HOME}/gnupg"

# set display to work with xterm
export DISPLAY=:0

##########################################################################
unset WIN_USER
