#!/usr/bin/env bash

## Create a new directory and enter it
function mkcd() {
   mkdir -p "$@" && cd "$_";
}

## Enter an directory and ls
function cdls() {
  cd $1 && ls
}

## Check if is WSL
function is_wsl() {
  return $(grep -q Microsoft /proc/version)
}

## Quickly go back to a specific parent directory
# Adapted from https://github.com/vigneshwaranr/bd
function bd() {
  local oldpwd=$(pwd)
  
  pattern=$1
  local newpwd=$(echo $oldpwd | perl -pe 's|(.*/'$pattern'[^/]*/).*|$1|i')

  if [ "$newpwd" = "$oldpwd" ]; then
    echo "No such occurrence."
  else
    echo $newpwd
    cd "$newpwd"
  fi
}
