#!/usr/bin/env bash

DOCKER_CUSTOM="${XDG_CONFIG_HOME}/docker/docker-custom"

##########################################################################
## EXPORTS

export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
export DOCKER_HOST="$(cat "${XDG_DATA_HOME}/docker/host")"
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="${STORAGE}/ssl/docker"


##########################################################################
## ALIASES

alias dockered="${EDITOR} ${DOCKER_CUSTOM}"
alias dockerrel="source ${DOCKER_CUSTOM}"
