#!/usr/bin/env bash

export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"

#export IPYTHONDIR="${XDG_CONFIG_HOME}/jupyter"
#export JUPYTERLAB_SETTINGS_DIR ="${XDG_CONFIG_HOME}/jupyter/user-settings"
#export JUPYTERLAB_WORKSPACES_DIR="{XDG_CACHE_HOME}/jupyter/workspaces"
