#!/usr/bin/env bash
CONDA_ENVS_BK_PATH="${PROJECTS}/conda_env_bk"
CONDA_ROOT_DIR=$(conda info | grep "base env" | grep -o '/[^ ]*')

##########################################################################
## EXPORTS

# Conda
export CONDARC="${XDG_CONFIG_HOME}/conda/condarc"
export CONDA_ENVS_DIRS="${XDG_DATA_HOME}/conda/envs"
export CONDA_PKGS_DIRS="${XDG_CACHE_HOME}/conda/pkgs"

# Jupyter
export IPYTHONDIR="${XDG_DATA_HOME}/ipython"

export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export JUPYTER_DATA_DIR="${XDG_DATA_HOME}/jupyter"
export JUPYTER_RUNTIME_DIR="${XDG_CACHE_HOME}/jupyter"

export JUPYTERLAB_SETTINGS_DIR="${XDG_CONFIG_HOME}/jupyter/user-settings"
export JUPYTERLAB_WORKSPACES_DIR="${XDG_CACHE_HOME}/jupyter/workspaces"

##########################################################################
## ALIASES

alias ccr="conda create"
alias cer="conda env remove"
alias cac="source ${CONDA_ROOT_DIR}/bin/activate"
alias cde="conda deactivate"
alias cin="conda install"
alias cee="conda env export"
alias ceefh="cee --from-history"
alias cel="conda env list"

#alias cinlt="conda install python=$(get_python_last_version)"

##########################################################################
## FUNCTIONS

function conda-backup-envs {
  local NOW=$(date "+%Y-%m-%d")
  local BK_PATH="${CONDA_ENVS_BK_PATH}/envs-${NOW}"
  local ENVS=$(conda env list | grep '^\w' | cut -d' ' -f1)
  mkdir $BK_PATH

  for ENV in $ENVS; do
    echo "Exporting $ENV"
    cac "${ENV}"
    ceefh > "${BK_PATH}/${ENV}.yml"
    cde
  done
}

function conda-restore-envs {
  #TODO
  return
}

function jupyter-lab {
  cac jupyter
  jupyter lab
  cde
}
