#!/usr/bin/env bash

##########################################################################
## EXPORTS

export NODE_REPL_HISTORY="${XDG_CACHE_HOME}/node/node_repl_history"

##########################################################################
## ALIASES

# alias to setup nodejs development environment
alias node-dev='export NODE_ENV=development'

# alias to setup nodejs production environment
alias node-prod='export NODE_ENV=production'
