#!/usr/bin/env bash

ASDF_CUSTOM="${XDG_CONFIG_HOME}/asdf/asdf-custom"

##########################################################################
## EXPORTS

export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
#exports ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=".tool-versions"

##########################################################################
## ALIASES

alias asdfed="${EDITOR} ${ASDF_CUSTOM}"
alias asdfrel="source ${ASDF_CUSTOM}"

##########################################################################
## FUNCTIONS

if [[ -d "/opt/asdf" ]]; then
  source "/opt/asdf/asdf.sh"
  source "/opt/asdf/completions/asdf.bash"
fi
