#!/usr/bin/env bash

##########################################################################
## EXPORTS

export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
#exports ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=".tool-versions"

##########################################################################
## ALIASES


##########################################################################
## FUNCTIONS


# Start ASDF
if [[ -d "/opt/asdf" ]]; then
  source "/opt/asdf/asdf.sh"
  source "/opt/asdf/completions/asdf.bash"
fi
