#!usr/bin/env bash

[[ -z "${TMUX}" ]] && tmux

##########################################################################
## EXPORTS

[[ ! -z "${TMUX}" ]] && TERM="screen-256color"
export TMUX_TMPDIR="${XDG_CACHE_HOME}/tmux"

##########################################################################
## ALIASES

alias tmux='tmux -f "${XDG_CONFIG_HOME}"/tmux/tmux.conf'
